sudo: required

language: python

services:
  - docker

branches:
  only:
  - master

notifications:
  email:
    on_failure: always
    recipients:
      - f339339@gmail.com

python:

  - "3.5"
  - "3.6"  # current default Python on Travis CI
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest -v tests/

before_deploy:
  - docker build . -t house_pred_env
  - docker run -it house_pred_env 
  - docker images
  - docker ps -a 

deploy:
  provider: script
  script: echo "REGISTRY_PASS $REGISTRY_PASS" && echo "REGISTRY_USER $REGISTRY_USER" && export REGISTRY_PASS=$REGISTRY_PASS && export REGISTRY_USER=$REGISTRY_USER && bash script/deploy_dockerhub.sh
  on:
    branch: master

# after_deploy:
#   - coverage run tests/test_api.py
#   - coverage run tests/test_predict.py 
#   - coverage report
#   - coveralls
