sudo: required

language: python

services:
  - docker

branches:
  only:
  - master

notifications:
  email:
    on_failure: always
    recipients:
      - f339339@gmail.com
python:

  - "3.5"
  - "3.6"  # current default Python on Travis CI
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest -v tests/
  - coverage run tests/test_api.py
  - coverage run tests/test_predict.py 

build:
  - docker build . -t env
  - docker images
  - docker ps -a 

after_success:
  - coverage report
  - coveralls
